### ISSUE TITLE
Killed: 9 on macOS Sierra

### ISSUE THREAD

**Issue by robgas** [seladb/PcapPlusPlus#99]
Hi,

I am trying to read a 60 GB pcap file with the following code but after few minutes the app is killed with error Killed: 9 because it's using to much memory:
```
int main(int argc, char* argv[])
{
  // open a pcap file for reading
  pcpp::PcapFileReaderDevice reader("60GBFile.pcap");
  if (!reader.open())
  {
    printf("Error opening the pcap file\n");
    return 1;
  }
  pcpp::RawPacket rawPacket;
  int packetCounters = 0;
  pcpp::Packet* parsedPacket;
  while (reader.getNextPacket(rawPacket))
  {
    packetCounters += 1;
    parsedPacket = new pcpp::Packet(&rawPacket, true);
    parsedPacket = NULL;
    delete parsedPacket;
  }
  printf("Total packets = %d d\n", packetCounters);
  reader.close();
  return 0;
}
```
The app works correctly without the creation of parsedPacket so I'm trying to clear the object but the app is always stopped with Killed:9.

**Comment by echo-Mike** [comment]
Hi, @robgas here are several problems with your code:  
1. You do not dealllocate allocated packet because you nullify the pointer  
2. You do not need to allocate a packet because you do not use its methods  

If you just remove next lines your program will work as expected:  
```C++
    parsedPacket = new pcpp::Packet(&rawPacket, true);
    parsedPacket = NULL;
    delete parsedPacket;
```

**Comment by robgas** [comment]
Hi @echo-Mike,
I need of parsedPacket object to use its methods and layers (like parsedPacket.getLayerOfType).

**Comment by seladb** [comment]
You should probably reverse the order of deleting `parsedPacket`:

    parsedPacket = new pcpp::Packet(&rawPacket, true);
    delete parsedPacket;
    parsedPacket = NULL;

**Comment by seladb** [comment]
@robgas please let us know if it solved your issue

**Comment by robgas** [comment]
@seladb I've tried your code and the following error is raised:
```
Tutorial-HelloWorld(15934,0x7fffaa7123c0) malloc: *** error for object 0x7fff5be5f858: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```
This happens for the **true** parameter in new pcpp::Packet that forces to call the raw packet destructor.
A workaround could be to limit the parsing of the packets to the IPv4 protocol (from TCP protocol too much memory is allocated).
```
parsedPacket = new pcpp::Packet(&rawPacket, true, pcpp::IPv4);
```
It seems like there is a memory leak in the creation of Packet.
This is the summary of  **valgrind --leak-check=full --show-leak-kinds=all** with a 12 MB pcap file:
```
==16550== LEAK SUMMARY:
==16550==    definitely lost: 685,161 bytes in 12,225 blocks
==16550==    indirectly lost: 1,771,946 bytes in 24,443 blocks
==16550==      possibly lost: 472 bytes in 8 blocks
==16550==    still reachable: 19,648 bytes in 140 blocks
==16550==         suppressed: 50,345 bytes in 162 blocks
```

**Comment by seladb** [comment]
@robgas thanks for the analysis. You should actually call `pcpp::Packet` c'tor with `freeRawPacket = false`, that should solve the error. Could you please try it and let me know if it worked?

**Comment by robgas** [comment]
@seladb It works of course. However the main issue is not resolved.

**Comment by seladb** [comment]
I'm not sure I'm following you. Could you please attach your code and explain what is not working (including the specific errors, etc.)?

**Comment by robgas** [comment]
Maybe I was not clear. The "Abort trap: 6" error has been resolved at the time I wrote the comment. 
The main issue is trying to read a huge pcap file (> 60Gb) without loosing the L7 protocols support and TCP Reassembly feature, something that happens when I create a Packet parsing until the pcpp::IPv4 layer. 
Have you ever tried to read a really huge pcap file?

**Comment by seladb** [comment]
So what happens when you don't try to limit the parsing to IPv4? do you get an exception then?
If yes, then it's probably an ubnormal packet that PcapPlusPlus doesn't know how to handle. If you can identify this packet and send it to me in a pcap file I can take a look and hopefully provide a fix

**Comment by robgas** [comment]
The issue seems like enabling the parsing of from TCP layer to up there is a huge and increasing memory allocation. It seems like the complete pcap file is copied in RAM. 
So the issue doesn't depend on an ubnormal packet but on a huge pcap file.
I think that the best way to find out the issue is to try to read a huge pcap file.

**Comment by seladb** [comment]
I'll refer to the code you wrote at the beginning of the thread: since you're deleting the parsed packet in each iteration, no packet data is stored between packets, so there should be no difference between parsing up until IPv4 or full parsing in terms of memory allocation.

Since you say that when parsing up until IPv4 everything works, I still suspect that specific packet(s) cause this issue

**Comment by seladb** [comment]
Did you have a chance to check this?

**Comment by seladb** [comment]
Since I didn't see any reply on the last 2.5 I'm closing this issue now. Please reopen it if needed
